/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import heap.Heap;

public class Huffman {

    public static void main(String[] args) {
        Heap heap = new Heap();
    }
}
